### PR TITLE
Initial set up

### PR DESCRIPTION
**Pull request by hanpeter**

### CODE REVIEW

**Comment by joestump** [comment]
What use cases do you see this solving over just using [`requests`](http://docs.python-requests.org/en/master/) or `curl`?

**Comment by hanpeter** [comment]
I did this because I do not like how I have to keep going `url='https://example.com/api/some/magic'`. I was hoping to just do `url='some/magic'` and the library fills it back in. Also, I find myself re-implementing the error handling a lot.

However, I am fully aware that this sounds like "Anything you can do, I can do better" library. I didn't want to be a JavaScript developer. So that's why I am asking whether we want something like this.

**Comment by dllopis-sfdc** [comment]
I’m having trouble connecting the dots. You’re building a `krux.cli` wrapper, but what you describe you want sounds like a `requests` wrapper.

**Comment by joestump** [comment]
I tend to do something like this when that pops up:

```python
import requests

BASE_URL = 'https://example.com/api{0}'
resp = requests.get(BASE_URL.format('/some/magic'))
```

If we are going to introduce a wrapper, I'd prefer we do something [like this](https://stackoverflow.com/questions/42601812/python-requests-url-base-in-session) that works with the internals of the library rather than wrapping it.

**Comment by sfdc-slumos** [comment]
If you are just trying to avoid repetition, then do what @joestump said. If you want to reduce typing and improve readability, then try *(copied from SO)*:

```python
from urlparse import urljoin
import requests

class RelativeSession(requests.Session):
    def __init__(self, base_url):
        super(RelativeSession, self).__init__()
        self.__base_url = base_url

    def request(self, method, url, **kwargs): 
        url = urljoin(self.__base_url, url)
        return super(RelativeSession, self).request(method, url, **kwargs)

session = RelativeSession('http://server.net')
response = session.get('/rel/url')
```

https://stackoverflow.com/questions/17045550/urllib2-requests-and-http-relative-path/28337825#28337825

Of course for readability you would not name the session variable `session`...

**Pull request closed without merging**
